<?xml version="1.0" encoding="utf-8"?><Database Name="QLNhaThuoc" Class="DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MACKENO\SQLEXPRESS;Initial Catalog=QLNhaThuoc;Integrated Security=True" SettingsObjectName="QLThuoc.Properties.Settings" SettingsPropertyName="QLNhaThuocConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Thuoc" Member="Thuocs">
    <Type Name="Thuoc">
      <Column Name="MaThuoc" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenThuoc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DonViTinh" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="DonGiaMua" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonGiaBan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Thuoc_ChiTietHoaDon" Member="ChiTietHoaDons" ThisKey="MaThuoc" OtherKey="MaThuoc" Type="ChiTietHoaDon" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietHoaDon" Member="ChiTietHoaDons">
    <Type Name="ChiTietHoaDon">
      <Column Name="MaHoaDon" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaThuoc" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DonGia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Thuoc_ChiTietHoaDon" Member="Thuoc" ThisKey="MaThuoc" OtherKey="MaThuoc" Type="Thuoc" IsForeignKey="true" />
      <Association Name="HoaDon_ChiTietHoaDon" Member="HoaDon" ThisKey="MaHoaDon" OtherKey="MaHoaDon" Type="HoaDon" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DoiTac" Member="DoiTacs">
    <Type Name="DoiTac">
      <Column Name="MaDoiTac" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDoiTac" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LaNhaCungCap" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="DoiTac_HoaDon" Member="HoaDons" ThisKey="MaDoiTac" OtherKey="MaDoiTac" Type="HoaDon" />
    </Type>
  </Table>
  <Table Name="dbo.v_ThongTinChiTietHoaDon" Member="v_ThongTinChiTietHoaDons">
    <Type Name="v_ThongTinChiTietHoaDon">
      <Column Name="MaHoaDon" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaThuoc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenThuoc" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DonViTinh" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DonGia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThanhTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDon" Member="HoaDons">
    <Type Name="HoaDon">
      <Column Name="MaHoaDon" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NgayHoaDon" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="MaDoiTac" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HoaDonMua" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Association Name="HoaDon_ChiTietHoaDon" Member="ChiTietHoaDons" ThisKey="MaHoaDon" OtherKey="MaHoaDon" Type="ChiTietHoaDon" />
      <Association Name="DoiTac_HoaDon" Member="DoiTac" ThisKey="MaDoiTac" OtherKey="MaDoiTac" Type="DoiTac" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_ThongTinHoaDon" Member="v_ThongTinHoaDons">
    <Type Name="v_ThongTinHoaDon">
      <Column Name="MaHoaDon" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NgayHoaDon" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="MaDoiTac" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenDoiTac" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HoaDonMua" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.v_ThongTinThuocCon" Member="v_ThongTinThuocCons">
    <Type Name="v_ThongTinThuocCon">
      <Column Name="MaThuoc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenThuoc" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DonViTinh" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="DonGiaMua" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonGiaBan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_BaoCaoDanhThu" Member="v_BaoCaoDanhThus">
    <Type Name="v_BaoCaoDanhThu">
      <Column Name="NgayHoaDon" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TenDoiTac" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="ThanhTienMuaHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThanhTienBanHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_ThongTinThuocTonKho" Member="v_ThongTinThuocTonKhos">
    <Type Name="v_ThongTinThuocTonKho">
      <Column Name="MaThuoc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenThuoc" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SoLuongMua" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuongBan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TonKho" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>